export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"

export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_FAIL = "PRODUCT_FAIL"

export const NEW_REVIEV_SUCCESS = "NEW_REVIEV_SUCCESS"
export const NEW_REVIEV_REQUEST = "NEW_REVIEV_REQUEST"
export const NEW_REVIEV_RESET = "NEW_REVIEV_RESET"
export const NEW_REVIEV_FAIL = "NEW_REVIEV_FAIL"

// Admin 

export const CLEAR_ERRORS = "CLEAR_ERRORS"